### ISSUE TITLE
Allow the change of mustache delimiters

### ISSUE THREAD

**Issue by gerlocian** [rogeriopvl/gulp-mustache#16]
I'm working on a project now that is using mustache as a build dependency, and we have need to change the delimiters for mustache so that they don't compete with delimiters from other frameworks. I was wondering if a "tags" option could be added that could allow us to change the delimiters for mustache.

    gulp.src('./src/**/*.html)
        .pipe(mustache({}, { 'tags': [ '{{m', 'm}}' ] }, {})
        .pipe(gulp.dest('./dist/');

At this point, the mustache delimiters would be set so that "{{m value m}}" would be the mustache delimiters instead of "{{ value }}". I know that mustache out of the box supports this, but I haven't been able to get it to work with "{{={{m m}}=}}", and would like to try to avoid adding that to all of my templates.

**Comment by gerlocian** [comment]
I just discovered that I can change the delimiters myself in a round about way using gulp-mustache-plus:

    var mustache = require('gulp-mustache-plus/node_modules/mustache'),
        gmustache = require('gulp-mustache-plus');

Then:

    mustache.tags = [ '{{m', 'm}}' ];
    gulp.src('./src/**/*.html)
        .pipe(gmustache({}, {}, {
            head: 'src/head.mustache'
        })
        .pipe(gulp.dest('./dist/');

Finally in template:

    {{m> head m}}

With this I can do my project properly. Thanks!

**Comment by rogeriopvl** [comment]
I'm curious about the solution you found. Theoretically it should also work with `gulp-mustache` since you're only changing the mustache package directly :)

**Comment by gerlocian** [comment]
Yes. In fact it should work like this for gulp-mustache. However I noticed on line 66 in index.js that the regex you are using for the partials match assumes that the delimiters have never changed. This is where it tripped me up.

**Comment by rogeriopvl** [comment]
oh, I get it now. Thanks for reporting this. I'll try to fix it ASAP.

**Comment by rogeriopvl** [comment]
@gerlocian You can now pass the tags into `gulp-mustache` options. And the regex issue is also fixed.

**Comment by gerlocian** [comment]
Awesome! Just tested it out and it works perfectly. Thanks!
