### ISSUE TITLE
Ability to lazily initialize view parameters 

### ISSUE THREAD

**Issue by binarykitchen** [rogeriopvl/gulp-mustache#18]
We have a case here where we'd like to initialize some view parameters inside the pipe, lazily. For example reading other file contents and passing this onto the template.

The stream returned from `through.obj()` has no functionality to set a single view parameter afterwards. I know it is difficult to achieve something like this.

Do you have any ideas/suggestions how to crack this one?

**Comment by rogeriopvl** [comment]
I'm afraid I don't have a solution for that right now. I'll be open to suggestions also.

**Comment by binarykitchen** [comment]
Never mind, the solution is so simple: mustache also accepts functions for view parameters. That solved it.

**Comment by rogeriopvl** [comment]
oh great! completely forgot about that feature :)
