### ISSUE TITLE
"Error: Cannot read property 'emit' of undefined" when partial loading fails

### ISSUE THREAD

**Issue by ericmorandbi** [rogeriopvl/gulp-mustache#20]
When a partial load fails, the following exception is raised instead of the exception that actually happened: "Error: Cannot read property 'emit' of undefined"

Step to reproduce:

1/ Create a template
2/ Add a reference to a non existing template: {{> nonExistingTemplate}}
3/ Compile

**Comment by rogeriopvl** [comment]
This is weird. I can't test it right now, is the error on line https://github.com/rogeriopvl/gulp-mustache/blob/master/index.js#L79 ?

**Comment by ericmorandbi** [comment]
Yes, this line exactly.

Le 4 déc. 2015 8:50 PM, Rogério Vicente <notifications@github.com> a écrit :

This is weird. I can't test it right now, is the error on line https://github.com/rogeriopvl/gulp-mustache/blob/master/index.js#L79 ?

-

**Comment by rogeriopvl** [comment]
Fix released as `v2.0.2`
