### ISSUE TITLE
mustache.render errors are uncaught

### ISSUE THREAD

**Issue by AlbertoElias** [rogeriopvl/gulp-mustache#27]
Maybe wrapping it in a try catch and emit that error on the stream? It would be very useful to catch the error in a _stream_ way. These errors are basically mustache syntax errors like unclosed sections

**Comment by AlbertoElias** [comment]
@rogeriopvl Thanks for the quick update! If you need any help, let me know. This is my test case template file that I would like to catch the error safely on:

```mustache
<div>
	{{#invalid-syntax}{{/invalid-syntax}}
</div>
```

**Comment by rogeriopvl** [comment]
Fixed on #28 and released as `v2.2.0`.

**Comment by AlbertoElias** [comment]
That works great! Thanks! :)
