### ISSUE TITLE
Warning on unknown variables

### ISSUE THREAD

**Issue by MatthijsZw** [rogeriopvl/gulp-mustache#39]
Sometimes we make typos on variable names (even with autosuggest). It would be great if gulp-mustache could generate a warning on 'unknown' variables, instead of giving back an empty string.

The Mustache man-page says:

`By default a variable "miss" returns an empty string. This can usually be configured in your Mustache library. The Ruby version of Mustache supports raising an exception in this situation, for instance.`

**Comment by rogeriopvl** [comment]
Hey @MatthijsZw, gulp-mustache is just a wrapper around [mustache.js](https://github.com/janl/mustache.js/). And AFAIK, there's currently no way to configure this behaviour on the js library. So you should ask this on their repo instead.

**Comment by MatthijsZw** [comment]
Thanks! I've done a new issue in their repo: https://github.com/janl/mustache.js/issues/599
