### ISSUE TITLE
Can't use different JSON files as source and a template as the parameter?

### ISSUE THREAD

**Issue by Tobsta** [rogeriopvl/gulp-mustache#44]
I have one template, error.mustache, and two JSON files, 404.json and 500.json. I would ideally like to be able to do the following:

```js
gulp.src("./*.json")
    .pipe(mustache({
        template: "error.mustache"
    }))
    .pipe(gulp.dest("./dist"));
```

However, the API seems to only support the other way around. I would have thought that using a template would mean using the same template for multiple configurations, but I dunno. I've tried the above code and using a glob like `{view: ./*.json}` as config, but neither worked properly.

**Comment by rogeriopvl** [comment]
Hi @Tobsta, 

`gulp-mustache` is just a wrapper around mustachejs library. So please check the [mustache api](https://github.com/janl/mustache.js/) for more info regarding your issue.

**Comment by Tobsta** [comment]
The order in which the API receives the files in, whether that be templates piped in and views passed as parameters, or views piped in and a template used to render them all, ends up with the work mustache does staying the same.

The feature that I feel is missing is missing from the gulp-mustache API, not mustache itself.
