### ISSUE TITLE
allow a rename to .html

### ISSUE THREAD

**Issue by ShashankaNataraj** [rogeriopvl/gulp-mustache#9]
This plugin produces a .mustache file as the output. Would like to request the author to add an option to change the extension to .html as well.

**Comment by rogeriopvl** [comment]
Please check the README file. `gulp-mustache` supports custom file extensions in `options.extension`.

**Comment by ShashankaNataraj** [comment]
Ah ok, RTFM fixes it for me again! Thanks!!

**Comment by Freak613** [comment]
It's very funny that plugin which supposed to produce resolved html files from mustache templates, can't do it by default. What is the usecase of .mustache output?

**Comment by rogeriopvl** [comment]
@Freak613 please check #4

**Comment by dzackgarza** [comment]
Thanks for the great plugin! Just wanted to point out that (as sort of a newcomer) the documentation for this isn't entirely obvious. It currently says
```
options.extension

Type: string Default: the extension of the current file
```

It might be worth adding some wording just explaining that this effects the _output_ extension of the file being processed. At first glance, I thought this option just determined what extensions it matched input files against.

Got it worked out though! So if anyone else stumbles across the same issue,  something like this works:

```javascript
gulp.src("./templates/*.mustache")
  .pipe(mustache({
      someTemplateVar: "myValue"
    }, { 
      extension: '.html' 
    }))
  .pipe(gulp.dest(BUILD_PATH));
